main_wifi_ssid: "ENTER_YOUR_MAIN_WIFI_SSID_HERE!!!"
main_wifi_password: "ENTER_YOUR_MAIN_WIFI_PASSWORD_HERE!!!"
secondary_wifi_ssid: "ENTER_YOUR_SECONDARY_WIFI_SSID_HERE!!!"
secondary_wifi_password: "ENTER_YOUR_SECONDARY_WIFI_PASSWORD_HERE!!!"
fallback_hotspot_password: "ENTER_YOUR_FALLBACK_HOTSPOT_PASSWORD_HERE!!!"
web_server_username: "ENTER_YOUR_WEBUI_LOGIN_HERE!!!"
web_server_password: "ENTER_YOUR_WEBUI_PASSWORD_HERE!!!"
